version: '2.1'

services:
  mqttdb:
    container_name: mqttdb
    image: redis:4-alpine
    ports:
      - "6379:6379" # HOST:CONTAINER
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=mqtt
    #  - MONGO_INITDB_ROOT_PASSWORD=mqtt1234
    healthcheck:
      test: exit 0
    env_file:
     - compose.env
  mqttbroker:
    container_name: mqttbroker
    build: .
    ports:
      - "1883:1883"
    depends_on:
      mqttdb:
        condition: service_healthy
    links:
      - mqttdb
    restart: on-failure
    env_file:
     - compose.env
