version: '2.1'

services:
  temperaturedb:
    container_name: temperaturedb
    image: mongo:3.4
    ports:
      - "27017:27017" # HOST:CONTAINER
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=mqtt
    #  - MONGO_INITDB_ROOT_PASSWORD=mqtt1234
    healthcheck:
      test: exit 0
    env_file:
     - compose.env
  temperature:
    container_name: temperature
    build: .
    ports:
      - "5000:5000" # HOST:CONTAINER
    depends_on:
      temperaturedb:
        condition: service_healthy
    links:
      - temperaturedb
    restart: on-failure
    env_file:
     - compose.env
